### ISSUE TITLE
Unable to download Tempus Maledictum - Lodgen Output.7z with Wabbajack

### ISSUE THREAD

**Issue by Anubitus** [LivelyDismay/tempus-maledictum#2]
Hi

I have a problem when trying to install the Tempus Maledictum modpack through Wabbajack. I restarted the Wabbajack program multiple times but i keep getting the same errors. Hope you can help.

The download of the "Tempus Maledictum - Lodgen Output.7z" file keeps failing. When checking the log the final part says:

00:11:36.178 [INFO] (Wabbajack.Installer.StandardInstaller) Optimized 262602 directives to 262602 required
00:11:36.216 [INFO] (Wabbajack.Installer.StandardInstaller) Next Step: Hashing Archives
00:11:36.216 [INFO] (Wabbajack.Installer.StandardInstaller) Looking for files to hash
00:11:36.216 [INFO] (Wabbajack.Installer.StandardInstaller) Getting archive sizes
00:11:36.236 [INFO] (Wabbajack.Installer.StandardInstaller) Linking archives to downloads
00:11:36.236 [INFO] (Wabbajack.Installer.StandardInstaller) Found 1891 total files, 1683 matching filesize
00:11:36.363 [INFO] (Wabbajack.Installer.StandardInstaller) Missing 1 archives
00:11:36.363 [INFO] (Wabbajack.Installer.StandardInstaller) Downloading validation data
00:11:36.577 [INFO] (Wabbajack.Installer.StandardInstaller) Validating Archives
00:11:36.577 [INFO] (Wabbajack.Installer.StandardInstaller) Downloading missing archives
00:11:36.577 [INFO] (Wabbajack.Installer.StandardInstaller) Downloading 1 archives
00:11:36.577 [INFO] (Wabbajack.Installer.StandardInstaller) Next Step: Downloading files
00:11:36.577 [INFO] (Wabbajack.Installer.StandardInstaller) Downloading Tempus Maledictum - Lodgen Output.7z
00:13:29.940 [INFO] (Wabbajack.Downloaders.DownloadDispatcher) Finished downloading Tempus Maledictum - Lodgen Output.7z. Hash: AAAAAAAAAAA=; Size: 138MB/1,9GB
00:13:30.236 [FATAL] (Wabbajack.Downloaders.DownloadDispatcher) While finding mirror for Hu2ejSRnvjQ=|System.NullReferenceException: Object reference not set to an instance of an object.
   at Wabbajack.Downloaders.WabbajackCDNDownloader.Download(Archive archive, WabbajackCDN state, AbsolutePath destination, IJob job, CancellationToken token) in C:\oss\wabbajack\Wabbajack.Downloaders.WabbajackCDN\WabbajackCDNDownloader.cs:line 83
   at Wabbajack.Downloaders.WabbajackCDNDownloader.Download(Archive archive, WabbajackCDN state, AbsolutePath destination, IJob job, CancellationToken token) in C:\oss\wabbajack\Wabbajack.Downloaders.WabbajackCDN\WabbajackCDNDownloader.cs:line 121
   at Wabbajack.Downloaders.DownloadDispatcher.Download(Archive a, AbsolutePath dest, Job`1 job, CancellationToken token, Nullable`1 useProxy) in C:\oss\wabbajack\Wabbajack.Downloaders.Dispatcher\DownloadDispatcher.cs:line 112
   at Wabbajack.Downloaders.DownloadDispatcher.Download(Archive a, AbsolutePath dest, CancellationToken token, Nullable`1 proxy) in C:\oss\wabbajack\Wabbajack.Downloaders.Dispatcher\DownloadDispatcher.cs:line 54
   at Wabbajack.Downloaders.DownloadDispatcher.DownloadFromMirror(Archive archive, AbsolutePath destination, CancellationToken token) in C:\oss\wabbajack\Wabbajack.Downloaders.Dispatcher\DownloadDispatcher.cs:line 245
00:13:30.236 [ERROR] (Wabbajack.Installer.StandardInstaller) Downloaded hash AAAAAAAAAAA= does not match expected hash: Hu2ejSRnvjQ=
00:13:30.236 [INFO] (Wabbajack.Installer.StandardInstaller) Next Step: Hashing Archives
00:13:30.236 [INFO] (Wabbajack.Installer.StandardInstaller) Looking for files to hash
00:13:30.236 [INFO] (Wabbajack.Installer.StandardInstaller) Getting archive sizes
00:13:30.264 [INFO] (Wabbajack.Installer.StandardInstaller) Linking archives to downloads
00:13:30.264 [INFO] (Wabbajack.Installer.StandardInstaller) Found 1891 total files, 1683 matching filesize
00:13:30.434 [FATAL] (Wabbajack.Installer.StandardInstaller) Unable to download Tempus Maledictum - Lodgen Output.7z (WabbajackCDNDownloader+State|https://authored-files.wabbajack.org/Tempus Maledictum - Lodgen Output.7z_2cb181e0-a8cf-492f-805c-6dc1ee92c4e2)
00:13:30.434 [FATAL] (Wabbajack.Installer.StandardInstaller) Cannot continue, was unable to download one or more archives
00:18:41.889 [ERROR] (Wabbajack.ModListGalleryVM) Error downloading modlist image Ascalon
00:18:41.889 [ERROR] (Wabbajack.ModListGalleryVM) Error downloading modlist image Ascalon

**Comment by Anubitus** [comment]
While waiting for a answer i restarted Wabbajack over and over and eventually it started downloading the file. Problem solved itself.

Thank you for the all the work you put into this awesome modpack, i cant wait to play it.
